### ISSUE TITLE
Dropdown menu for a correct answer button

### ISSUE THREAD

**Issue by danielmapar** [PiETLab/TreasureBoxBrailleApps#9]
From TBB created by [saraAzari](https://github.com/saraAzari) : biltzerpos/TBB#67  

- New scenario
- Trying to ask a question
- Drop menu to choose the correct button 
- Menu has no options to pick from-- does not work

**Comment by DylMB** [comment]
This issue was fixed sometime between the migration and now.
The menu for the "correct answer button" now has options corresponding to the number of buttons for the scenario.
